return {
  { 'ibhagwan/fzf-lua', branch='main' },
  { 'tpope/vim-commentary' },
  { "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} },
  { 'akinsho/bufferline.nvim', version = "*", dependencies = 'nvim-tree/nvim-web-devicons' },
  { 'nvim-lualine/lualine.nvim' },
  { 'nvim-tree/nvim-web-devicons' },
  { 'neanias/everforest-nvim', branch='main' },
  { 'tpope/vim-fugitive' },
  { 'tpope/vim-sleuth' },
  { 'lewis6991/gitsigns.nvim' },
  { 'bfrg/vim-cpp-modern' },
  { 'szw/vim-maximizer' },
  { 'Shougo/echodoc.vim' },
  { 'akinsho/toggleterm.nvim' },
  { 'nvim-treesitter/nvim-treesitter', build=':TSUpdate' },
  { 'nvim-treesitter/nvim-treesitter-context' },
  { 'folke/noice.nvim' },
  { 'MunifTanjim/nui.nvim' },
  { 'rcarriga/nvim-notify' },
  { 'williamboman/mason.nvim' },
  { 'williamboman/mason-lspconfig.nvim' },
  { 'neovim/nvim-lspconfig' },
  { 'WhoIsSethDaniel/toggle-lsp-diagnostics.nvim' },
  { 'sindrets/diffview.nvim' },
  { 'cappyzawa/trim.nvim', opts = {} },
  { 'Bekaboo/deadcolumn.nvim' },
  { 'hrsh7th/nvim-cmp' },
  { 'hrsh7th/cmp-nvim-lsp' },
  { 'saadparwaiz1/cmp_luasnip' },
  { 'L3MON4D3/LuaSnip' },
  {
      "chrisgrieser/nvim-spider",
      keys = {
          {
              "e",
              "<cmd>lua require('spider').motion('e')<CR>",
              mode = { "n", "o", "x" },
          },
          {
              "w",
              "<cmd>lua require('spider').motion('w')<CR>",
              mode = { "n", "o", "x" },
          },
          {
              "b",
              "<cmd>lua require('spider').motion('b')<CR>",
              mode = { "n", "o", "x" },
          },
      },
  },
}
