add_newline = true

format = """
$directory\
$username\
$character"""

right_format = """
$git_commit\
$git_state\
$cmd_duration\
$jobs\
$status"""

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '

[hostname]
format = '[ $ssh_symbol $hostname]($style) '
ssh_symbol = "🌐"

[c]
disabled = true
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '[ ⏱  $duration]($style)'

[conda]
format = '[$symbol $environment]($style)'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[git_branch]
disabled = false
format = '[ $symbol$branch]($style)'
style = 'fg:cyan'

[git_status]
disabled = true
format = '([$all_status$ahead_behind]($style))'

[git_state]
disabled = false
style = 'fg:blue'

[git_commit]
disabled = false
style = 'fg:blue'

[golang]
format = '[$symbol($version)]($style)'

[lua]
format = '[$symbol($version)]($style)'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = 'py'
format = '\[[${symbol}(\($virtualenv\))]($style)\]'

[rust]
format = '[$symbol ($version)]($style)'

[sudo]
format = '[as $symbol]'

[time]
format = '[$time]($style)'

[username]
disabled = true
format = '\[[$user]($style)\]'
